# File: pull_request.yaml

#parameters:
#  - name: 'package'
#    default: false

jobs:
  - job: Build
    steps:
      # Build artifacts
      - script: yarn
        displayName: Install Packages
#      - script: yarn lint
#        displayName: linting
      - script: yarn test
        displayName: unit testing
      - script: yarn build
        displayName: build
      # - script: yarn start:container && yarn test-integration
      #   displayName: IntegrationTest

  - job: Package
#    condition: and(succeeded(), eq(variables['package'], true))
    dependsOn: Build
    steps:
      # Run to package
      - script: yarn install
        displayName: prune dependencies

      - script: yarn pack
      - task: DeleteFiles@1
        inputs:
          Contents: '"node_modules"'
      - task: DeleteFiles@1
        inputs:
          Contents: '"Tests"'
      # publish package as artifact

      - task: CopyFiles@2
        inputs:
          TargetFolder: "$(Build.ArtifactStagingDirectory)/functionapp"

      - task: ArchiveFiles@1
        inputs:
          rootFolder: "$(Build.ArtifactStagingDirectory)/FunctionApp"
          includeRootFolder: "false"
          archiveFile: "$(Build.ArtifactStagingDirectory)/FunctionApp.zip"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/FunctionApp.zip"
          ArtifactName: "drop"
          ArtifactType: "Container"

    
  