# File: pull_request.yaml

#parameters:
#  - name: 'package'
#    default: false

jobs:
  - job: Build
    steps:
      # Build artifacts
      - script: yarn
        displayName: Install Packages
#      - script: yarn lint
#        displayName: linting
      - script: yarn test
        displayName: unit testing
      - script: yarn build
        displayName: build

      - task: DeleteFiles@1
        inputs:
          Contents: '"node_modules"'
      - task: DeleteFiles@1
        inputs:
          Contents: '"Tests"'
      # publish package as artifact

      - task: CopyFiles@2
        inputs:
          TargetFolder: "$(Build.ArtifactStagingDirectory)/nodedemoapp-v1.0.0.tgz"

      - task: ArchiveFiles@1
        inputs:
          rootFolder: "$(Build.ArtifactStagingDirectory)/nodedemoapp-v1.0.0.tgz"
          includeRootFolder: "false"
          archiveFile: "$(Build.ArtifactStagingDirectory)/nodedemoapp-v1.0.0.tgz"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/Functionapp.zip"
          ArtifactName: "drop"
          ArtifactType: "Container"

    
  