parameters:
  buildLocation: ''
  environment: ''
  azureSubscription: ''
  resourceGroupName: ''
  appName: ''
  notifyUsers: ''

jobs:
#  - job: CreateQASlot
#    displayName: QA Slot creation  
#    pool:
#       vmImage: 'windows-latest'   
#    steps:
#      - task: AzureCLI@2
#        inputs:
#          azureSubscription: 'WorkDemoSusc(591cb3b2-9ae6-48d4-b103-babcec6f0b2d)'
#          scriptType: 'ps'
#          scriptLocation: 'inlineScript'
#          inlineScript: 'az functionapp deployment slot create --name FunctionAppAPM --resource-group functionappapm --slot QA' 

  - deployment: DeployApp
    displayName: deploy Function App
#    dependsOn: CreateQASlot
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
#        preDeploy:
#          steps:
#            - script: |
#                echo It will grab tagged zip directory for app
        deploy:
          steps:
            - task: AzureFunctionApp@1
              displayName: Deploy to QA slot
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                appType: functionApp
                appName: ${{ parameters.appName }}
                package: ${{ parameters.buildLocation }}
                deployToSlotOrASE: true
                slotName: QA

  #Enable these steps when the smoke tests for the QA slot are created 
        #postRouteTraffic:
        #  steps:
        #    - script: |
        #        echo run the QA smoke test
        # on:
        #   failure:
        #     steps: echo drop failed slot
        #   success:
        #     steps:
        #        - task: AzureAppServiceManage@0
        #          inputs:
        #            azureSubscription: ${{ parameters.azureSubscription }}
        #            Action: 'Swap Slots'
        #            WebAppName: ${{ parameters.appName }}
        #            ResourceGroupName: ${{ parameters.resourceGroupName }}
        #            SourceSlot: 'QA'

#Temporary jobs created for manual approval until QA smoke tests are created
  - job: waitForValidation
    displayName: Wait for external validation  
    dependsOn: DeployApp  
    pool: server    
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:   
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: ${{ parameters.notifyUsers }}
          instructions: 'Please validate the build configuration and resume'

  - deployment: Swap
    displayName: Swap to prod
    dependsOn: waitForValidation  
    pool:
      name: Hosted VS2017
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        preDeploy:
          steps:
            - script: |
                echo do all the things before deploy
        deploy:
          steps:                
            - task: AzureAppServiceManage@0
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                Action: 'Swap Slots'
                WebAppName: ${{ parameters.appName }}
                ResourceGroupName: ${{ parameters.resourceGroupName }}
                SourceSlot: 'QA'
        on:
#          failure:
#            steps: echo drop failed slot
          success:
            steps:
              - task: AzureAppServiceManage@0
                inputs:
                  azureSubscription: ${{ parameters.azureSubscription }}
                  Action: 'Delete Slot'
                  WebAppName: ${{ parameters.appName }}
                  ResourceGroupName: ${{ parameters.resourceGroupName }}
                  Slot: 'QA'